In [2]:
###comparing execution time of numpy and panda
import time
import numpy as np
size_vector = 1000000
def pure_python_v():
    time_python = time.time()
    py_lst1 = range(size_vector)
    py_lst2 = range(size_vector)
    sum_pylist = [py_lst1[i] + py_lst2[i] for i in range(len(py_lst1))]
    return time.time() - time_python
def pure_numpy_v():
    time_numpy = time.time()
    nm_lst1 = np.arange(size_vector)
    nm_lst2 = np.arange(size_vector)
    sum_nmlst = nm_lst1 + nm_lst2
    return time.time() - time_numpy
python_time = pure_python_v()
numpy_time = pure_numpy_v()
print("python time is {:0.4f}".format(python_time))
print("numpy time is {:0.4f}".format(numpy_time))
print("numpy is {:0.4f} times faster python".format(python_time/numpy_time))

python time is 0.2112
numpy time is 0.0088
numpy is 24.1221 times faster python


In [23]:
my_pylst = [1, 2, 3, 4, 5]
print('Type: ', type(my_pylst))
print('Python lst concan: ', my_pylst + my_pylst)
np_array = np.array(my_pylst)
print('Type nplst: ', type(np_array))
print('Numpy arry concan: ', np_array + np_array)
print('numpy arry shape: {}\n size: {}\n resolution: {}\n datatype {}\n '
      .format(np_array.shape, np_array.size, np_array.ndim, np_array.dtype))

Type:  <class 'list'>
Python lst concan:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Type nplst:  <class 'numpy.ndarray'>
Numpy arry concan:  [ 2  4  6  8 10]
numpy arry shape: (5,)
 size: 5
 resolution: 1
 datatype int64
 


In [27]:
#Creating 2D array using 
my_pyListoLst = [[1, 2, 3, 4],[5, 6, 7, 8]]
my_npyListoLst = np.array(my_pyListoLst)
print('my numpy 2d array type is ', type(my_npyListoLst))
print('my numpy array which is 2d is ', my_npyListoLst)
print('array shape: {}\n size: {}\n resolution: {}\n datatype {}\n'
      .format(my_npyListoLst.shape, my_npyListoLst.size, my_npyListoLst.ndim, my_npyListoLst.dtype))

my numpy 2d array type is  <class 'numpy.ndarray'>
my numpy array which is 2d is  [[1 2 3 4]
 [5 6 7 8]]
array shape: (2, 4)
 size: 8
 resolution: 2
 datatype int64



In [28]:
my_pynlist = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
my_pynnpylist = np.array(my_pynlist)
print('numpy list type is ', type(my_pynnpylist))
print('numpy list is ', my_pynnpylist)
print('array shape: {}\n size: {}\n resolution: {}\n datatype {}\n '
      .format(my_pynnpylist.shape, my_pynnpylist.size, my_pynnpylist.ndim, my_pynnpylist.dtype))

numpy list type is  <class 'numpy.ndarray'>
numpy list is  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array shape: (4, 3)
 size: 12
 resolution: 2
 datatype int64
 


In [25]:
my_3dpylist = [[[1, 1], [1, 1]],
              [[2, 2], [2, 2]]]
my_3dnpyarry = np.array(my_3dpylist)
print('type of npy array ', type(my_3dnpyarry))
print('numpy array ', my_3dnpyarry)
print('array shape: {}\n size: {}\n resolution: {}\n datatype {}\n '
      .format(my_3dnpyarry.shape, my_3dnpyarry.size, my_3dnpyarry.ndim, my_3dnpyarry.dtype))

type of npy array  <class 'numpy.ndarray'>
numpy array  [[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]]
array shape: (2, 2, 2)
 size: 8
 resolution: 3
 datatype int64
 


In [30]:
print('first: ', np.arange(5))
print('second: ', np.arange(2,5,2))
print('third: ',np.arange(2,5))

first:  [0 1 2 3 4]
second:  [2 4]
third:  [2 3 4]


In [31]:
np.linspace(0, 3, 12)

array([0.        , 0.27272727, 0.54545455, 0.81818182, 1.09090909,
       1.36363636, 1.63636364, 1.90909091, 2.18181818, 2.45454545,
       2.72727273, 3.        ])

In [44]:
np_zero = np.zeros(5)
print(np_zero)
print(np.zeros(5,int))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [37]:
t_dim_zeroes = np.zeros(shape=(4,4))
print('shape', t_dim_zeroes.ndim)
print(t_dim_zeroes)

shape 2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [50]:
a = np.array([1,2,3])
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.empty_like(a))
print(np.full_like(a,5))


[0 0 0]
[1 1 1]
[1 1 1]
[5 5 5]


In [68]:
print('numpy 1D random arry: ',np.random.rand(2))
print(np.random.randn(4))
print(np.random.randint(0,10,5))
print(np.random.uniform(0,7,2))
print(np.random.normal(0,8,2))
print('numpy 2D random arry: ', np.random.rand(2,2))

numpy 1D random arry:  [0.79084843 0.23021594]
[0.46902785 1.03588957 0.64663532 2.06653278]
[6 5 2 6 3]
[5.04662016 3.12939632]
[0.51094623 8.86059564]
numpy 2D random arry:  [[0.22599886 0.91152438]
 [0.68410293 0.95539664]]


In [75]:
rand_array = np.random.rand(8)
print(rand_array)
print(rand_array.reshape(4,2))
print(np.random.rand(10).reshape(2,5))

[0.41818458 0.50899293 0.94793423 0.3111788  0.64776714 0.05709548
 0.69551178 0.85272398]
[[0.41818458 0.50899293]
 [0.94793423 0.3111788 ]
 [0.64776714 0.05709548]
 [0.69551178 0.85272398]]
[[0.06330114 0.07366298 0.14613327 0.01583208 0.65031936]
 [0.60591485 0.90295302 0.46202965 0.89169653 0.51699707]]


In [97]:
arr_Ops = np.arange(12).reshape(4,3)
print('arr_ops: ', arr_Ops)
print('complete second row: ',arr_Ops[1,:])
print('1st row, 3rd column: ', arr_Ops[0,1])
print('complete last column: ', arr_Ops[:,-1])
print('2 from first 2 rows and columns: ', arr_Ops[0:2,0:2])
print('last 2 from rows and columns: ', arr_Ops[2:,1:])

arr_ops:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
complete second row:  [3 4 5]
1st row, 3rd column:  1
complete last column:  [ 2  5  8 11]
2 from first 2 rows and columns:  [[0 1]
 [3 4]]
last 2 from rows and columns:  [[ 7  8]
 [10 11]]


In [99]:
#broadcasting
a = np.array([2,3,4])
b = 3
print(a*b)

[ 6  9 12]


In [104]:
#2broadcasting
arr_2D = np.array([[1,2,3],[5,6,7],[8,9,10],[12,13,14]])
scalar = 3
print('shape of array: ', arr_2D.shape)
print('add of 2d array with scalar: ', arr_2D + scalar)
arr_1D = np.array([15,15,15])
print('add 2darray with 1 d array: ', arr_2D + arr_1D)

shape of array:  (4, 3)
add of 2d array with scalar:  [[ 4  5  6]
 [ 8  9 10]
 [11 12 13]
 [15 16 17]]
add 2darray with 1 d array:  [[16 17 18]
 [20 21 22]
 [23 24 25]
 [27 28 29]]


In [107]:
arr_x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_y = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print('concat by axis 1: ',np.concatenate((arr_x,arr_y),axis=1))
print('concat by axis 0: ',np.concatenate((arr_x,arr_y),axis=0))

concat by axis 1:  [[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
concat by axis 0:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
